// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticasLDP3.Datos;

#nullable disable

namespace PracticasLDP3.Migrations
{
    [DbContext(typeof(AbmContext))]
    partial class AbmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticasLDP3.Modelos.Alumno", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<string>("ApellidoNombre")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidonom");

                    b.Property<string>("Provincia")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("provincia");

                    b.HasKey("Dni");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("PracticasLDP3.Modelos.Usuario", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nombre");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clave");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mail");

                    b.HasKey("Nombre");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
